include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  errors:
    # Ignore deprecation warnings for DropdownButtonFormField.value
    # We need to use value instead of initialValue for dynamic updates
    deprecated_member_use: ignore
